export const CLIENT_ID = process.env.NEXT_PUBLIC_CALENDLY_CLIENT_ID;
export const CLIENT_SECRET = process.env.NEXT_PUBLIC_CALENDLY_CLIENT_SECRET;
export const REDIRECT_URI = process.env.NEXT_PUBLIC_CALENDLY_REDIRECT_URI;